### ISSUE TITLE
Inscrição

### ISSUE THREAD

**Issue by hebertom** [layonsonofre/propesp-eaic#2]
Quando uma pessoa se cadastra para o evento pelos seguintes botões listados a seguir, em quais tabelas eu devo inserir respectivamente?

"Quero compartilhar"

"Quero aprender"

"Quero Ajudar"
      - monitor
      - coordenador de sessão

**Comment by layonsonofre** [comment]
Foi apenas uma tentativa na interface, vou remover no próximo commit pois não faz sentido deixar logo na página inicial.
