### ISSUE TITLE
Criar blades separados

### ISSUE THREAD

**Issue by marciogurka** [layonsonofre/propesp-eaic#7]
Criar blades separados para o Header, Footer e Scripts, dessa forma esses blades são carregados só uma vez e só é trocado o "meio", ou o conteúdo deles, nas páginas principais.

**Comment by layonsonofre** [comment]
E também headers separados para cada tipo de usuário logado

**Comment by marciogurka** [comment]
Não seria melhor criar um único Header com todas as regras de acesso de cada tipo de usuário? Assim fica um único blade de Header

**Comment by layonsonofre** [comment]
Boa, o que ficar mais fácil de trabalhar! :+1:

**Comment by marciogurka** [comment]
Menus da área comum (acesso geral) já colocados em um único arquivo.
